<package format="3">
  <name>robot_interfaces</name>
  <version>0.0.1</version>
  <description>自定义消息和服务接口</description>
  <maintainer email="student@robot.com">student</maintainer>
  <license>Apache-2.0</license>

  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <depend>geometry_msgs</depend>
  <member_of_group>rosidl_interface_packages</member_of_group>
</package>
